### ISSUE TITLE
dosent work

### ISSUE THREAD

**Issue by ireadyhater1** [theplummer/ScoresMatter#2]
when i activated it and clicked on the like drop down bar to see if i got it right or wrong it gave me an error saying that it couldnt get the send or something like that

**Comment by theplummer** [comment]
Uh can you provide a screenshot or something? I can't diagnose the issue without actual media of the issue.

**Comment by belocrazed** [comment]
Hi

**Comment by theplummer** [comment]
This issue has been fixed btw, and I will push the update soon. Give me until January 31.

**Comment by theplummer** [comment]
Ok I FINALLY pushed the update. Closing.
