### ISSUE TITLE
[Bug?] answers don’t show in drop-down menu anymore after going to another question 

### ISSUE THREAD

**Issue by DoIoco** [theplummer/ScoresMatter#4]
I don’t really know how to duplicate this bug but I did try to rerun the script but it didn’t work 

Device: School-managed iPad
Browsers it has: Safari, Chrome

I also bookmarkified the script so I could use it on the iPad

also password doesn’t show.

I’ll send proof tomorrow

**Comment by DoIoco** [comment]
i cannot sumbit it so ill just send a youtube link

**Comment by theplummer** [comment]
I got this issue too recently. I fixed it, and I will upload the update soon.

**Comment by theplummer** [comment]
Sorry for the wait, I really thought I would have more time to update this since it was literally winter break, but I've been caught up with other things. Give me until January 31.
